2020-07-31 00:50:57.502654: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-31 00:50:57.517502: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.518059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-07-31 00:50:57.518200: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-31 00:50:57.519330: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-31 00:50:57.520370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-31 00:50:57.520544: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-31 00:50:57.521662: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-31 00:50:57.522263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-31 00:50:57.524696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-31 00:50:57.524805: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.525410: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.525824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-07-31 00:50:57.526010: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-07-31 00:50:57.529896: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4200000000 Hz
2020-07-31 00:50:57.530126: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a9a68c2770 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-31 00:50:57.530138: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-31 00:50:57.530288: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.530834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-07-31 00:50:57.530869: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-31 00:50:57.530881: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-31 00:50:57.530899: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-31 00:50:57.530912: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-31 00:50:57.530924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-31 00:50:57.530935: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-31 00:50:57.530946: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-31 00:50:57.530994: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.531569: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.531957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-07-31 00:50:57.531978: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-31 00:50:57.672168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-31 00:50:57.672186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-07-31 00:50:57.672191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-07-31 00:50:57.672336: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.672663: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.672965: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-31 00:50:57.673274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10341 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-07-31 00:50:57.674471: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a9a7db6b30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-31 00:50:57.674483: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
2020-07-31 00:51:00.709361: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-31 00:51:01.143956: W tensorflow/stream_executor/gpu/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-07-31 00:51:01.163112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-31 00:51:02.199301: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-07-31 00:51:02.199332: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1259] Profiler found 1 GPUs
2020-07-31 00:51:02.199794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
2020-07-31 00:51:02.300222: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-07-31 00:51:02.301850: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-07-31 00:51:02.442883: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-07-31 00:51:02.442920: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.



MODEL:cnn_dice_EXTDATApp_augmentation_small
Train for 1928 steps, validate for 13 steps
Epoch 1/100

Epoch 00001: val_loss improved from inf to 0.14127, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 261s - loss: 0.1404 - accuracy: 0.9516 - f1: 0.8565 - mean_io_u: 0.8503 - val_loss: 0.1413 - val_accuracy: 0.9519 - val_f1: 0.8829 - val_mean_io_u: 0.8665
Epoch 2/100

Epoch 00002: val_loss improved from 0.14127 to 0.13282, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1405 - accuracy: 0.9515 - f1: 0.8550 - mean_io_u: 0.8520 - val_loss: 0.1328 - val_accuracy: 0.9561 - val_f1: 0.8928 - val_mean_io_u: 0.8769
Epoch 3/100

Epoch 00003: val_loss improved from 0.13282 to 0.13093, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1365 - accuracy: 0.9528 - f1: 0.8594 - mean_io_u: 0.8561 - val_loss: 0.1309 - val_accuracy: 0.9574 - val_f1: 0.8950 - val_mean_io_u: 0.8796
Epoch 4/100

Epoch 00004: val_loss did not improve from 0.13093
1928/1928 - 257s - loss: 0.1342 - accuracy: 0.9535 - f1: 0.8608 - mean_io_u: 0.8591 - val_loss: 0.1412 - val_accuracy: 0.9542 - val_f1: 0.8885 - val_mean_io_u: 0.8734
Epoch 5/100

Epoch 00005: val_loss did not improve from 0.13093
1928/1928 - 257s - loss: 0.1356 - accuracy: 0.9530 - f1: 0.8587 - mean_io_u: 0.8575 - val_loss: 0.1361 - val_accuracy: 0.9561 - val_f1: 0.8929 - val_mean_io_u: 0.8774
Epoch 6/100

Epoch 00006: val_loss did not improve from 0.13093
1928/1928 - 257s - loss: 0.1328 - accuracy: 0.9539 - f1: 0.8620 - mean_io_u: 0.8586 - val_loss: 0.1772 - val_accuracy: 0.9437 - val_f1: 0.8606 - val_mean_io_u: 0.8459
Epoch 7/100

Epoch 00007: val_loss did not improve from 0.13093
1928/1928 - 257s - loss: 0.1340 - accuracy: 0.9536 - f1: 0.8617 - mean_io_u: 0.8592 - val_loss: 0.1407 - val_accuracy: 0.9554 - val_f1: 0.8900 - val_mean_io_u: 0.8747
Epoch 8/100

Epoch 00008: val_loss did not improve from 0.13093
1928/1928 - 257s - loss: 0.1326 - accuracy: 0.9539 - f1: 0.8620 - mean_io_u: 0.8590 - val_loss: 0.1470 - val_accuracy: 0.9526 - val_f1: 0.8837 - val_mean_io_u: 0.8678
Epoch 9/100

Epoch 00009: val_loss did not improve from 0.13093
1928/1928 - 257s - loss: 0.1316 - accuracy: 0.9543 - f1: 0.8635 - mean_io_u: 0.8605 - val_loss: 0.1376 - val_accuracy: 0.9538 - val_f1: 0.8865 - val_mean_io_u: 0.8703
Epoch 10/100

Epoch 00010: val_loss improved from 0.13093 to 0.12805, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1296 - accuracy: 0.9546 - f1: 0.8644 - mean_io_u: 0.8601 - val_loss: 0.1281 - val_accuracy: 0.9566 - val_f1: 0.8949 - val_mean_io_u: 0.8794
Epoch 11/100

Epoch 00011: val_loss did not improve from 0.12805
1928/1928 - 257s - loss: 0.1315 - accuracy: 0.9541 - f1: 0.8631 - mean_io_u: 0.8617 - val_loss: 0.1311 - val_accuracy: 0.9557 - val_f1: 0.8939 - val_mean_io_u: 0.8777
Epoch 12/100

Epoch 00012: val_loss improved from 0.12805 to 0.12764, saving model to checkpoints/ckp_cnn_dice_EXTDATApp_augmentation_small.h5
1928/1928 - 257s - loss: 0.1280 - accuracy: 0.9552 - f1: 0.8667 - mean_io_u: 0.8645 - val_loss: 0.1276 - val_accuracy: 0.9567 - val_f1: 0.8945 - val_mean_io_u: 0.8788
